[project]
name = "companion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "spacer", email = "f-balykin@mail.ru" }
]
requires-python = ">=3.14"
dependencies = [
    "aiogram>=3.31.0",
    "aiohttp-socks>=0.12.0",
    "companion-core",
    "faster-whisper>=1.2.1",
    "faststream[rabbit]>=0.7.5",
    "openai-agents>=0.22.0",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.15.0",
    "pyvips>=3.2.0",
]

[project.scripts]
companion = "companion:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "companion-core",
]

[tool.uv.sources]
companion-core = { workspace = true }
