import inspect
from collections.abc import Callable
from typing import Any, Protocol, get_type_hints

from openai.types.chat import ChatCompletionFunctionToolParam
from pydantic import create_model


class FuncTool(Callable, Protocol):
    tool_schema: ChatCompletionFunctionToolParam


def tool(func: Callable) -> FuncTool:
    """
    Decorator that attaches an OpenAI tool schema (.openai_schema)
    to a function based on its type hints and docstring.
    """
    sig = inspect.signature(func)
    type_hints = get_type_hints(func)

    # 1. Build Pydantic model fields dynamically from function signature
    fields = {}
    for name, param in sig.parameters.items():
        if name in ("self", "cls"):
            continue

        # Extract parameter type hint (default to Any if omitted)
        param_type = type_hints.get(name, Any)

        # Determine default value
        if param.default is inspect.Parameter.empty:
            default_val = ...  # Required field in Pydantic
        else:
            default_val = param.default

        fields[name] = (param_type, default_val)

    # 2. Dynamically create a Pydantic model for parameter validation & schema extraction
    model_name = f"{func.__name__}_args"  # ty: ignore[unresolved-attribute]
    ArgsModel = create_model(model_name, **fields)  # ty: ignore[no-matching-overload]

    # 3. Extract JSON schema generated by Pydantic
    parameters_schema = ArgsModel.model_json_schema()

    # Clean up Pydantic-specific metadata keys OpenAI doesn't use
    parameters_schema.pop("title", None)

    # 4. Construct OpenAI Function/Tool structure
    schema = {
        "type": "function",
        "function": {
            "name": func.__name__,  # ty: ignore[unresolved-attribute]
            "description": (inspect.getdoc(func) or "").strip(),
            "parameters": parameters_schema,
            "strict": True,
        },
    }

    # Attach schema to the decorated function
    func.tool_schema = schema  # ty: ignore[unresolved-attribute]
    return func  # ty: ignore[invalid-return-type]


class ToolManager:
    def __init__(self) -> None:
        self._registry: dict[str, FuncTool] = {}

    def register(self, func: Callable) -> None:
        func_tool = tool(func)
        tool_name = func_tool.tool_schema["function"]["name"]
        self._registry[tool_name] = func_tool

    def execute(self, name: str, kwargs: dict[str, Any]) -> Any:
        func_tool = self._registry.get(name)

        if not func_tool:
            raise ValueError(f"Tool '{name}' not found.")

        return func_tool(**kwargs)

    async def aexecute(self, name: str, kwargs: dict[str, Any]) -> Any:
        func_tool = self._registry.get(name)

        if not func_tool:
            raise ValueError(f"Tool '{name}' not found.")

        if inspect.iscoroutinefunction(func_tool):
            return await func_tool(**kwargs)
        return func_tool(**kwargs)
